### ISSUE TITLE
[Feature Request] Adding NZB-files through the share sheet to SABnzbd/NZBGet

### ISSUE THREAD

**Issue by xBotRaid** [LunaSeaApp/LunaSea#157]
This would be an easy-to-integrate feature, but would make things quite a bit easier. Instead of adding a NZB through the Files-app you'd have the option to load the NZB directly onto the Server via the share sheet. Same feature is already present in the apps "NZB Search", "NZBClient for NZBGet" or "WhatSAB".

[Here](https://pasteboard.co/IVRGhyE.png) we see the screenshot of "NZB Search"s implementation.

**Comment by JagandeepBrar** [comment]
I'll take a look into this in the future, there's an added level of complexity compared to those applications because there is support for multiple clients in one app + multiple profiles, would have to add a clean way to allow a user to select the profile and client.

Not super high on the list of features right now, but I'll keep it in mind!

**Comment by JagandeepBrar** [comment]
Moved: https://feedback.lunasea.app/31
