### ISSUE TITLE
[Feature Request] support for viewing the download queue within other contexts

### ISSUE THREAD

**Issue by elmstreetvictim** [LunaSeaApp/LunaSea#183]
There are times when I am drilled down into a Sonarr/Radarr manual search, and selecting releases for queueing. In order to view my Sabnzbd download queue I have to completely back out of what I am looking at. That means going backwards from the search, backwards from the episode/movie, out of the Sonarr/Radarr view and into the Sabnzbd queue. 

It would be nice to have access to the Hamburger menu to quickly go to the download queue and stay exactly where I am in the navigation hierarchy  of my current context. 

Instead, as it is, if I back out to view my queue then I lose my place within the ‘arr apps and have to go back to where I was if my download was not satisfactory.

**Comment by JagandeepBrar** [comment]
The only problem is how to display the drawer, because default navigation style on iOS is that a left swipe of the screen goes back a page. Any suggestions?

**Comment by elmstreetvictim** [comment]
I haven’t looked at your source but I am familiar with Cocoa and NextStep. Maybe when you are starting an NZB download step (and the toast appears that download starting...) you could have it be tappable to launch a Modal view of your Sab queue. 

Or post an NSNotification and have your views listen for it, and provide a button or some way to bring up a modal window.

**Comment by JagandeepBrar** [comment]
> you could have it be tappable to launch a Modal view of your Sab queue.

Definitely an I tweeting supporting and possible! I’ll start taking a look into this soon.

**Comment by JagandeepBrar** [comment]
<img width="400" alt="Screen Shot 2020-04-09 at 12 27 46 AM" src="https://user-images.githubusercontent.com/3048295/78860900-f788a800-79f8-11ea-865f-9fdaae2603ab.png">

So I was able to add this in without a problem into the newznab indexer search there is now a "VIEW" button in the toast (which lasts longer, ~5 seconds when there is an action), but adding it into any of the -rr services is a more complex.

The issue here is I have no information on the client that these services send to. It could be one of the clients they have added to LunaSea, a completely different one, one in a different profile, etc.

For example someone can have 1 instance of SABnzbd, 1 instance of NZBGet, and 2 instances of Radarr, each connected to one of the prior clients.

If the user has added both SAB and NZBGet to one profile, there is no way to determine which client to go to. I could add a modal, but that's not clean/easy. I will continue to investigate the best options for that situation. For now though, Search will include this ability in the next TestFlight!

**Comment by JagandeepBrar** [comment]
Actually on the above, what I decided is a clean medium is there is now a "BACK" action on the toast which will pop you all the way back to the main screen of the service, giving you quick access to the drawer again, removing a lot of the back, back, back, back action.

It isn't the perfect solution, but it seems like the best middle ground to give you quick(er) access to the client of choice. This will also be included in the TestFlight build going live tonight/tomorrow morning!
