### ISSUE TITLE
[Bug] Adding a new series defaults to type "Anime"

### ISSUE THREAD

**Issue by hugepants** [LunaSeaApp/LunaSea#186]
**Describe the Bug**
Adding a new series will default to type `Anime`. If the type is changed, it will remember the chosen type but only while the app is running. If the app is force-closed, the series type will revert back to `Anime`.

**To Reproduce**
Start a fresh instance of LunaSea and add a new series.

**Expected Behaviour**
The default series type should be `Standard`. In addition, if the series type is changed after adding a new series, it should remember this change across sessions. This will mirror the behaviour of the Web GUI.

**Versions**
LunaSea v2.0.0 (333)
Sonarr 2.0.0.5344

**Comment by JagandeepBrar** [comment]
This will be changed to use the database instead of app-state in the next release (v2.1.0). I will update here it is live in TestFlight!

**Comment by JagandeepBrar** [comment]
https://github.com/LunaSeaApp/LunaSea/commit/fda1a034d798fec579e8fa8961bf8417f1787a87

I have changed the defaults of the following:

Radarr Minimum Availability: Defaults to "Announced" instead of "PreDB"
Sonarr Series Type: Defaults to "Standard" instead of "Anime"

Changes to making it stored in cold-state will take a bit more time, but on the roadmap. I am building a TestFlight release now, and will likely get approved in the next few days.

**Comment by hugepants** [comment]
Perfect, thanks for the quick response and resolution!

**Comment by JagandeepBrar** [comment]
Storing your add configuration in the database instead of app state has now been added to TestFlight v2.0.1 (22)!
