### ISSUE TITLE
[Bug] Toast notifications can cause locking of swipe-back gesture

### ISSUE THREAD

**Issue by julian-str** [LunaSeaApp/LunaSea#192]
Hi, i have had this bug a few times now. I think it only happens when there is a toast notification on screen.

The last time it happened I unmonitored a season in Sonarr and swiped left to right to get back to the menu while the toast notification was still on screen.
This is the result:
![image](https://user-images.githubusercontent.com/29665092/78945101-c32bef00-7abf-11ea-94ba-9debd55982a8.png)

I have had this happen a few times and not only when unmonitoring seasons. 

Additional Info:
iPhone 8 Plus                | iPhone 7
iOS 13.4.1                       | iOS 13.4.1
LunaSea 2.0.0 (333)     | LunaSea 2.0.1 (55)

Hopefully this is enough for you to replicate the bug and fix it.

It‘s not too much of a nusiance, because you can still click the arrow to go back but a fix would be appreciated.

For further questions or testing I will be at your service.
Thank you for such an amazing app!

**Comment by JagandeepBrar** [comment]
Thanks for the bug report!

I have been aware of this internally for a bit, looking into a solution.

It has to do with how the snackbar/toast is being handled as a route, so the “freeze” happens when the toast is dismissed (via the timeout) while swiping back, it thinks the route is closed.

I’ll try to give you an update soon, this has been bugging me for a while too.

**Comment by JagandeepBrar** [comment]
This has now been fixed and will be in the first TestFlight of v2.3.0 this week!

https://github.com/LunaSeaApp/LunaSea/commit/aef6b77ef0e06f08a2ead115b22c0afeadf12f72
