### ISSUE TITLE
[Feature Request] Notifications

### ISSUE THREAD

**Issue by myusuf3** [LunaSeaApp/LunaSea#21]
**Describe the solution you'd like**
Notifications for big downloads, and completed new downloads etc. 
**Additional context**
Simply a way to know what is happening when.

**Comment by JagandeepBrar** [comment]
I will have to take a look into a way I could do this that would fit the OSS format, since push notifications would require some kind of backend server to be running.

Another thing is that the app itself is just calling API calls, so I would have to create scripts that you would add into the services to run on import, download, etc.

Right now this is not a priority since it would require a large development time (if even possible to do in a OSS format), but I will keep the issue open because I would love to add it in eventually.

**Comment by JagandeepBrar** [comment]
Moved to: https://feedback.lunasea.app/10
