### ISSUE TITLE
[Feature Request] Remember options between sessions

### ISSUE THREAD

**Issue by simonk83** [LunaSeaApp/LunaSea#73]
I’m mostly talking about the “hide unmonitored” button here (I have to click that every time I open LunaSea), but it applies to everything I guess 😊

**Comment by JagandeepBrar** [comment]
This is an intended feature, but I just need to do some research on the best way. Currently the app uses [Shared Preferences](https://pub.dev/packages/shared_preferences), a common plugin to store data on the filesystem. I just want to do some research into the overhead of continuously writing to the shared preferences, and also the chances of corruption because that is also how the configuration are stored.

Regardless, I definitely want to have transparent-preference saving implemented ASAP.

**Comment by JagandeepBrar** [comment]
I have ultimately decided to store this in app (hot) state, not in database (cold) state. So during the entire time LunaSea is open, it will remember your sorting options, hide unmonitored choice, etc. even between changes of services, but will reset to default when doing a cold start of the app.

This is just more in-line with the norms/expectations of users, because these are commonly reset to the defaults on each load.

This might change in the future, I want to gather some feedback regarding the topic of what should and shouldn't be saved in cold state, but for now it will remain in hot state.
